In [8]:
import numpy as np

a = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


m = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])

cifra = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]])

print(m)

[[0 1 0]
 [1 0 0]
 [0 0 1]]


In [9]:
mc = np.dot(m, cifra)
print(mc)

[[0 0 1]
 [0 1 0]
 [1 0 0]]


In [12]:
nova_m = mc @ np.linalg.inv(cifra)
print(nova_m)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
